version: '3'

services:
  web:
    build: .
    environment:
      - FLASK_APP=hello.py
      - FLASK_ENV=development
    command: flask run --reload --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
